"""
DecodeOCR -- AI Image & Text Recognition Pipeline
Decode Labs Project 4: Image or Text Recognition (Basic)

Transforms raw visual data into machine-readable text using:
  - OpenCV (image pre-processing pipeline)
  - Tesseract OCR (text recognition engine)
  - Confidence-based output filtering (>=80% threshold)

Usage:
  python recognizer.py                          # Run with built-in sample image
  python recognizer.py --image path/to/img.png  # Run on your own image
  python recognizer.py --help                   # Full options
"""

import argparse
import csv
import os
import sys
import textwrap

import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont

# -----------------------------------------------------------
# Tesseract configuration
# -----------------------------------------------------------
# Point pytesseract at the installed engine
import pytesseract

pytesseract.pytesseract.tesseract_cmd = (
    r"C:\Program Files\Tesseract-OCR\tesseract.exe"
)

SAMPLE_FILENAME = "sample_input.png"
OUTPUT_DIR = "output"

# PSM modes we auto-scan (label, constant, description)
PSM_SCAN_MODES = [
    (3,  "Fully automatic"),
    (6,  "Single text block"),
    (7,  "Single text line"),
    (13, "Sparse text"),
]

CONFIDENCE_THRESHOLD = 80  # minimum % to include a word


# ============================================================
# Sample Image Generator
# ============================================================

def generate_sample_image(path: str) -> str:
    """
    Create a test image with known text on a gradient background
    with simulated noise, so the pre-processing pipeline has real
    work to do.  Returns the absolute path to the generated file.
    """
    width, height = 800, 300

    # --- Gradient background ---
    arr = np.zeros((height, width, 3), dtype=np.uint8)
    for y in range(height):
        t = y / height
        r = int(40 + t * 80)       # dark-ish gradient
        g = int(40 + t * 60)
        b = int(80 + t * 100)
        arr[y, :] = (r, g, b)

    # --- Gaussian noise ---
    noise = np.random.normal(0, 15, arr.shape).astype(np.int16)
    noisy = np.clip(arr.astype(np.int16) + noise, 0, 255).astype(np.uint8)

    img = Image.fromarray(noisy, "RGB")
    draw = ImageDraw.Draw(img)

    # --- Font ---
    font = None
    for candidate in [
        "C:\\Windows\\Fonts\\consola.ttf",
        "C:\\Windows\\Fonts\\cour.ttf",
        "C:\\Windows\\Fonts\\arial.ttf",
        "C:\\Windows\\Fonts\\segoeui.ttf",
    ]:
        if os.path.exists(candidate):
            try:
                font = ImageFont.truetype(candidate, 36)
            except Exception:
                continue
            break

    if font is None:
        font = ImageFont.load_default()

    # --- Text lines (known ground-truth for confidence evaluation) ---
    lines = [
        "DecodeLabs AI Project 4",
        "Image & Text Recognition Pipeline",
        "Confidence threshold: 80%",
    ]

    y_offset = 40
    for line in lines:
        # Light text so pre-processing must work to separate it
        draw.text((40, y_offset), line, fill=(210, 210, 240), font=font)
        y_offset += 60

    # --- Small secondary text to test multi-size recognition ---
    small_font = None
    if font and font.size >= 36:
        try:
            small_font = ImageFont.truetype(font.path, 18)
        except Exception:
            small_font = None
    if small_font is None:
        small_font = ImageFont.load_default()

    draw.text(
        (40, y_offset + 20),
        "Generated by DecodeOCR  |  PSM auto-scan  |  OpenCV + Tesseract",
        fill=(180, 180, 220),
        font=small_font,
    )

    img.save(path)
    return os.path.abspath(path)


# ============================================================
# Pre-Processing Pipeline
# ============================================================

def preprocess(image_path: str, debug: bool = False) -> np.ndarray:
    """
    Apply the IPO pre-processing pipeline:
      1. Grayscale conversion
      2. Gaussian blur (noise reduction)
      3. Otsu's adaptive thresholding (binary decision)

    When *debug* is True, saves each stage as a PNG inside OUTPUT_DIR
    for visual inspection.

    Returns the final binary image as a numpy array (usable by pytesseract).
    """
    img = cv2.imread(image_path)
    if img is None:
        raise FileNotFoundError(f"Cannot read image: {image_path}")

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # --- Step 1: Grayscale ---
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    if debug:
        cv2.imwrite(os.path.join(OUTPUT_DIR, "debug_01_grayscale.png"), gray)

    # --- Step 2: Gaussian Blur ---
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    if debug:
        cv2.imwrite(os.path.join(OUTPUT_DIR, "debug_02_blurred.png"), blurred)

    # --- Step 3: Otsu's Thresholding ---
    _, binary = cv2.threshold(
        blurred, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU
    )
    if debug:
        cv2.imwrite(os.path.join(OUTPUT_DIR, "debug_03_otsu.png"), binary)

    return binary


# ============================================================
# OCR Engine
# ============================================================

def _confidence_sort_key(item):
    """Sort key: highest confidence first."""
    return -item["conf"]


def run_ocr(image: np.ndarray, psm: int) -> dict | None:
    """
    Run Tesseract on *image* with a given *psm* mode.

    Returns a dict with keys:
      - raw_text:   full string output
      - words:      list of dicts {text, conf, left, top, w, h}
      - avg_conf:   mean confidence across all recognised words (0&#8211;100)
      - psm:        the PSM value used
    or None if nothing was recognised.
    """
    config = f"--psm {psm} --oem 3"
    try:
        data = pytesseract.image_to_data(
            image, config=config, output_type=pytesseract.Output.DICT
        )
    except pytesseract.TesseractError as e:
        print(f"  [!] Tesseract error with PSM {psm}: {e}")
        return None

    words = []
    n = len(data["text"])
    for i in range(n):
        text = data["text"][i].strip()
        conf = data["conf"][i]
        if text and conf != "-1":
            words.append({
                "text": text,
                "conf": int(conf),
                "left": int(data["left"][i]),
                "top": int(data["top"][i]),
                "w": int(data["width"][i]),
                "h": int(data["height"][i]),
            })

    if not words:
        return None

    avg_conf = sum(w["conf"] for w in words) / len(words)
    words.sort(key=_confidence_sort_key)

    raw_text = pytesseract.image_to_string(image, config=config).strip()

    return {
        "raw_text": raw_text,
        "words": words,
        "avg_conf": round(avg_conf, 1),
        "psm": psm,
    }


def scan_psm(image: np.ndarray, psm_modes: list, threshold: int) -> dict | None:
    """
    Try multiple PSM modes and return the result with the highest
    average confidence that also contains at least one word above
    *threshold*.
    """
    candidates = []
    for psm, label in [(m[0], m[1]) for m in psm_modes]:
        result = run_ocr(image, psm)
        if result is None:
            continue

        highest = max(w["conf"] for w in result["words"])
        print(
            f"  PSM {psm:>2} ({label:22s})  "
            f"words={len(result['words']):>3}  "
            f"avg_conf={result['avg_conf']:>5.1f}%  "
            f"peak={highest}%"
        )

        if highest >= threshold:
            candidates.append(result)

    if not candidates:
        return None

    # Pick the candidate with the highest average confidence
    candidates.sort(key=lambda r: r["avg_conf"], reverse=True)
    return candidates[0]


def filter_words(words: list, threshold: int) -> list:
    """Return only words whose confidence >= *threshold*."""
    return [w for w in words if w["conf"] >= threshold]


def build_annotated_image(
    original_path: str, words: list, output_path: str
) -> str:
    """
    Draw bounding boxes and confidence labels for all *words*
    onto the original image.  Saves to *output_path*.
    Returns the absolute path.
    """
    img = cv2.imread(original_path)
    h, w = img.shape[:2]

    for word in words:
        x, y, bw, bh = word["left"], word["top"], word["w"], word["h"]
        # Clamp within image bounds
        x, y = max(0, x), max(0, y)
        bw = min(bw, w - x)
        bh = min(bh, h - y)

        # Green box for >= threshold, orange for below
        color = (0, 200, 0) if word["conf"] >= CONFIDENCE_THRESHOLD else (0, 165, 255)
        cv2.rectangle(img, (x, y), (x + bw, y + bh), color, 2)

        label = f"{word['text']} ({word['conf']}%)"
        (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
        cv2.rectangle(img, (x, y - th - 4), (x + tw + 4, y), color, -1)
        cv2.putText(
            img, label, (x + 2, y - 2),
            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1,
        )

    cv2.imwrite(output_path, img)
    return os.path.abspath(output_path)


# ============================================================
# Export
# ============================================================

def export_text(text: str, path: str):
    """Write *text* to a UTF-8 file at *path*."""
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"  Exported text -> {os.path.abspath(path)}")


def export_csv(words: list, path: str):
    """Write per-word confidence data to CSV."""
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["text", "confidence_%", "left", "top", "width", "height"])
        for w in words:
            writer.writerow([w["text"], w["conf"], w["left"], w["top"], w["w"], w["h"]])
    print(f"  Exported data -> {os.path.abspath(path)}")


# ============================================================
# CLI
# ============================================================

def parse_args(argv: list | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="DecodeOCR -- AI Image & Text Recognition Pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              python recognizer.py
              python recognizer.py --image my_scan.png --psm 6
              python recognizer.py --image receipt.jpg --debug --export report.txt
              python recognizer.py --threshold 90 --no-auto-psm
        """),
    )
    parser.add_argument(
        "--image", "-i",
        default=None,
        help="Path to input image (default: generate a sample image)",
    )
    parser.add_argument(
        "--psm",
        type=int,
        default=None,
        help="Force a specific PSM mode (default: auto-scan all modes)",
    )
    parser.add_argument(
        "--threshold", "-t",
        type=int,
        default=CONFIDENCE_THRESHOLD,
        help=f"Minimum confidence %% to include a word (default: {CONFIDENCE_THRESHOLD})",
    )
    parser.add_argument(
        "--debug", "-d",
        action="store_true",
        help="Save pre-processing stage images to output/",
    )
    parser.add_argument(
        "--export", "-e",
        default=None,
        metavar="FILE",
        help="Export extracted text to FILE",
    )
    parser.add_argument(
        "--csv",
        default=None,
        metavar="FILE",
        help="Export per-word confidence data to CSV",
    )
    parser.add_argument(
        "--no-auto-psm",
        action="store_true",
        help="Skip PSM auto-scan; use PSM 3 (fully automatic) only",
    )
    return parser.parse_args(argv)


# ============================================================
# Main
# ============================================================

def main():
    args = parse_args()

    print("=" * 60)
    print("  DecodeOCR -- AI Image & Text Recognition Pipeline")
    print("  Project 4: Model Implementation (Mastery Phase)")
    print("=" * 60)

    # -------------------------------------------------------
    # 1. Resolve input image
    # -------------------------------------------------------
    image_path = args.image
    if image_path is None:
        print("\n[Stage 0] Generating sample image ...")
        image_path = generate_sample_image(SAMPLE_FILENAME)
        print(f"  Created -> {image_path}")
    else:
        if not os.path.exists(image_path):
            print(f"\n[!] File not found: {image_path}")
            sys.exit(1)

    print(f"\n[Input] {image_path}")
    img = cv2.imread(image_path)
    if img is None:
        print(f"[!] Cannot decode image (unsupported format or corrupt): {image_path}")
        sys.exit(1)
    print(f"  Dimensions: {img.shape[1]} x {img.shape[0]}  ({img.shape[2]} channels)")

    # -------------------------------------------------------
    # 2. Pre-processing
    # -------------------------------------------------------
    print("\n[Stage 1] Pre-processing pipeline ...")
    print("  Grayscale -> Gaussian Blur -> Otsu Thresholding")
    try:
        binary = preprocess(image_path, debug=args.debug)
    except FileNotFoundError as e:
        print(f"  [!] {e}")
        sys.exit(1)

    print(f"  Binary image: {binary.shape[1]} x {binary.shape[0]}")
    if args.debug:
        print(f"  Debug images saved to '{OUTPUT_DIR}/'")

    # -------------------------------------------------------
    # 3. OCR
    # -------------------------------------------------------
    print("\n[Stage 2] Optical Character Recognition ...")

    threshold = max(0, min(100, args.threshold))
    print(f"  Confidence filter: >= {threshold}%")

    if args.psm is not None:
        # Single PSM mode (forced)
        print(f"  PSM mode: {args.psm} (manually selected)")
        result = run_ocr(binary, args.psm)
    elif args.no_auto_psm:
        print("  PSM mode: 3 (fully automatic, --no-auto-psm set)")
        result = run_ocr(binary, 3)
    else:
        # Auto-scan
        print("  Auto-scanning PSM modes ...")
        result = scan_psm(binary, PSM_SCAN_MODES, threshold)

    if result is None:
        print("\n  [!] No text detected above the confidence threshold.")
        print("  Try: --threshold 50 (lower threshold) or --debug (inspect pre-processing)")
        sys.exit(0)

    print(f"\n  -- Best result: PSM {result['psm']} "
          f"(avg. confidence {result['avg_conf']}%) --")

    # -------------------------------------------------------
    # 4. Filter & Report
    # -------------------------------------------------------
    passed = filter_words(result["words"], threshold)
    rejected = [w for w in result["words"] if w["conf"] < threshold]

    print("\n[Stage 3] Confidence Report")
    print(f"  Total words detected:   {len(result['words'])}")
    print(f"  Passed (>= {threshold}%):     {len(passed)}")
    print(f"  Rejected (< {threshold}%):   {len(rejected)}")
    print(f"  Overall accuracy:       {result['avg_conf']}%")

    if passed:
        print(f"\n  -- Recognised Text (confidence >= {threshold}%) --")
        print()
        for w in passed:
            bar_len = max(1, w["conf"] // 10)
            bar = "#" * bar_len
            print(f"    {bar}  {w['text']:30s}  {w['conf']}%")

    if rejected:
        print("\n  -- Below Threshold (rejected) --")
        for w in rejected:
            print(f"    {w['text']:30s}  {w['conf']}%")

    # Raw text
    print("\n  -- Full Extracted Text --\n")
    print(textwrap.indent(result["raw_text"], "    "))
    print()

    # -------------------------------------------------------
    # 5. Annotated image
    # -------------------------------------------------------
    annotated_path = os.path.join(OUTPUT_DIR, "annotated_result.png")
    build_annotated_image(image_path, result["words"], annotated_path)
    print(f"  Annotated image -> {annotated_path}")

    # -------------------------------------------------------
    # 6. Export
    # -------------------------------------------------------
    if args.export:
        export_text(result["raw_text"], args.export)

    if args.csv:
        export_csv(result["words"], args.csv)

    print()
    print("=" * 60)
    print("  Project 4 complete -- Machine perception validated.")
    print("=" * 60)


if __name__ == "__main__":
    main()
